"""Evidence-locked Drosophila sensor-to-flight simulation interfaces."""

from .calibration import (
    ArtifactFile,
    CalibrationContractError,
    CalibrationEvidenceContract,
    CalibrationSplit,
    FitDiagnostic,
    FitProvenance,
    LicenseRecord,
    LicensedSource,
    MetricProtocol,
    PermanentSplitPlan,
    ProtocolReference,
    RedistributionStatus,
    TrialAssignment,
    TrialRecord,
    verify_artifact_files,
)
from .evidence import EvidenceEdge, EvidenceGraph, load_seed_graph
from .schema import (
    CircuitOutputTrace,
    DescendingTrace,
    FeedbackFrame,
    FlightEpisodeConfig,
    FlightEpisodeResult,
    MechanicsFrame,
    ModelRegistry,
    MuscleState,
    RetinalFrame,
    SideContext,
    WingMotorTrace,
)
from .nod1 import legacy_result_to_circuit_trace, load_legacy_nod1_manifest
from .fly_fgs_runtime import (
    FlyFGSCircuitCheckpoint,
    FlyFGSCircuitSample,
    FlyFGSRuntimeError,
    FlyFGSSceneBodyInput,
    NodeFlyFGSCircuitRuntime,
)
from .pipeline import (
    NOD1FlightPipelineConfig,
    NOD1FlightRun,
    load_legacy_nod1_result,
    nod1_run_to_web_replay,
    run_nod1_flight_pipeline,
    run_registered_fly_fgs_flight_pipeline,
    run_registered_nod1_browser_flight_pipeline,
    run_retinal_flight_pipeline,
    write_nod1_flight_artifact,
    write_nod1_web_replay,
)
from .validation import BenchmarkRegistry, ValidationReport, ValidationRunner
from .canonical_artifacts import (
    CANONICAL_ARTIFACT_SCHEMA_VERSION,
    CANONICAL_WEB_TRACE_SCHEMA_VERSION,
    CanonicalArrayBundle,
    bind_canonical_web_replay_to_artifact,
    canonical_array_bundle,
    canonical_closed_loop_to_web_replay,
    canonical_run_id,
    canonical_web_projection_sha256,
    write_canonical_closed_loop_artifact,
)

__version__ = "0.1.0"

__all__ = [
    "ArtifactFile",
    "CalibrationContractError",
    "CalibrationEvidenceContract",
    "CalibrationSplit",
    "FitDiagnostic",
    "FitProvenance",
    "LicenseRecord",
    "LicensedSource",
    "MetricProtocol",
    "PermanentSplitPlan",
    "ProtocolReference",
    "RedistributionStatus",
    "TrialAssignment",
    "TrialRecord",
    "verify_artifact_files",
    "CircuitOutputTrace",
    "DescendingTrace",
    "WingMotorTrace",
    "MuscleState",
    "FeedbackFrame",
    "FlightEpisodeConfig",
    "FlightEpisodeResult",
    "MechanicsFrame",
    "ModelRegistry",
    "RetinalFrame",
    "SideContext",
    "EvidenceEdge",
    "EvidenceGraph",
    "load_seed_graph",
    "legacy_result_to_circuit_trace",
    "load_legacy_nod1_manifest",
    "FlyFGSCircuitCheckpoint",
    "FlyFGSCircuitSample",
    "FlyFGSRuntimeError",
    "FlyFGSSceneBodyInput",
    "NodeFlyFGSCircuitRuntime",
    "NOD1FlightPipelineConfig",
    "NOD1FlightRun",
    "load_legacy_nod1_result",
    "nod1_run_to_web_replay",
    "run_nod1_flight_pipeline",
    "run_registered_fly_fgs_flight_pipeline",
    "run_registered_nod1_browser_flight_pipeline",
    "run_retinal_flight_pipeline",
    "write_nod1_flight_artifact",
    "write_nod1_web_replay",
    "BenchmarkRegistry",
    "ValidationReport",
    "ValidationRunner",
    "CANONICAL_ARTIFACT_SCHEMA_VERSION",
    "CANONICAL_WEB_TRACE_SCHEMA_VERSION",
    "CanonicalArrayBundle",
    "bind_canonical_web_replay_to_artifact",
    "canonical_array_bundle",
    "canonical_closed_loop_to_web_replay",
    "canonical_run_id",
    "canonical_web_projection_sha256",
    "write_canonical_closed_loop_artifact",
]
